### ISSUE TITLE
Attempted to run just after Setting up my .env got this error.

### ISSUE THREAD

**Issue by ram111222** [SecondRobotics/SimTourneyBot#11]
ERROR [2023-11-01 23:13:43]: error:1E08010C:DECODER routines::unsupported
    err: {
      "type": "Error",
      "message": "error:1E08010C:DECODER routines::unsupported",
      "stack":
          Error: error:1E08010C:DECODER routines::unsupported
              at Sign.sign (node:internal/crypto/sig:131:29)
              at Object.sign (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\jwa\index.js:152:45)
              at Object.jwsSign [as sign] (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\jws\lib\sign-stream.js:32:24)
              at GoogleToken.requestToken (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\gtoken\build\src\index.js:225:31)
              at GoogleToken.getTokenAsyncInner (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\gtoken\build\src\index.js:163:21)
              at GoogleToken.getTokenAsync (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\gtoken\build\src\index.js:142:55)
              at GoogleToken.getToken (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\gtoken\build\src\index.js:94:21)
              at JWT.refreshTokenNoCache (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\google-auth-library\build\src\auth\jwtclient.js:158:36)
              at JWT.refreshToken (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\google-auth-library\build\src\auth\oauth2client.js:143:25)
              at JWT.authorizeAsync (C:\Users\tamil\Desktop\SimTourneyBot-main\node_modules\google-auth-library\build\src\auth\jwtclient.js:139:35)
      "library": "DECODER routines",
      "reason": "unsupported",
      "code": "ERR_OSSL_UNSUPPORTED"
    }

**Comment by NicholasBottone** [comment]
This error appears to be a misconfiguration in your `.env` file, specifically pertaining to your GCP Service Worker. Please double check your `.env` config file, especially GOOGLE_SHEET_PRIVATE_KEY. I recommend reading through the [GCP setup instructions](https://github.com/SecondRobotics/SimTourneyBot/wiki/Set-up-Google-Sheet-and-Google-Sheets-API) on our wiki.

**Comment by ram111222** [comment]
I have ran back through it. It is correct and is still throwing this error.

**Comment by NicholasBottone** [comment]
Ensure `-----BEGIN PRIVATE KEY-----` and the corresponding closing tag are part of your key. Also ensure the `\n` characters are part of your key.

**Comment by ram111222** [comment]
Now its telling me there invalid 
C:\Users\tamil\Documents\GitHub\SimTourneyBot\node_modules\zod\lib\types.js:141
        throw result.error;
        ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "GOOGLE_SHEET_CLIENT_EMAIL"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "GOOGLE_SHEET_PRIVATE_KEY"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "GOOGLE_SHEET_DOC_ID"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "DISCORD_TOKEN"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "DISCORD_CLIENT_ID"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "DISCORD_GUILD_ID"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "DISCORD_CHANNEL_ID"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "DISCORD_CATEGORY_ID"
    ],
    "message": "Required"
  }
]
    at get error [as error] (C:\Users\tamil\Documents\GitHub\SimTourneyBot\node_modules\zod\lib\types.js:43:31)
    at ZodObject.parse (C:\Users\tamil\Documents\GitHub\SimTourneyBot\node_modules\zod\lib\types.js:141:22)
    at Object.<anonymous> (C:\Users\tamil\Documents\GitHub\SimTourneyBot\dist\config\env.js:17:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\tamil\Documents\GitHub\SimTourneyBot\dist\index.js:3:1) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'GOOGLE_SHEET_CLIENT_EMAIL' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'GOOGLE_SHEET_PRIVATE_KEY' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'GOOGLE_SHEET_DOC_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_TOKEN' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_CLIENT_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_GUILD_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_CHANNEL_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_CATEGORY_ID' ],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'GOOGLE_SHEET_CLIENT_EMAIL' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'GOOGLE_SHEET_PRIVATE_KEY' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'GOOGLE_SHEET_DOC_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_TOKEN' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_CLIENT_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_GUILD_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_CHANNEL_ID' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'DISCORD_CATEGORY_ID' ],
      message: 'Required'
    }
  ]
}

**Comment by ram111222** [comment]
Disregard last message. Mine just randomly started to work.

**Comment by ram111222** [comment]
Isboton = Ture 


If anyone is reading this with the same issue. Please make sure to have your env as .env and nothing else. Also make sure to use '' Whenever you have a key with spaces or any sort of strange symbole
